name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/gw2-addon-builder:$(date +%s)
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GHCR_ACCESS_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build and push image
      run: |
        docker build -t ghcr.io/jsantorek/gw2-addon-builder:latest .
        docker push ghcr.io/jsantorek/gw2-addon-builder:latest
